import "~/styles/globals.css";
import { NavBar } from "./_components/page";
import { GeistSans } from "geist/font/sans";
import  { ClerkProvider } from "@clerk/nextjs"


export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider> 
      <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col gap-4">
        <NavBar/>
        {children}</body>
    </html>
    </ClerkProvider>
    
  );
}
